import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        paper: {
          bg: 'var(--pq-bg-primary)',
          secondary: 'var(--pq-bg-secondary)',
          tertiary: 'var(--pq-bg-tertiary)',
          sidebar: 'var(--pq-sidebar)',
          surface: 'var(--pq-surface-1)',
          'surface-2': 'var(--pq-surface-2)',
          'surface-3': 'var(--pq-surface-3)',
          elevated: 'var(--pq-surface-elevated)',
          border: 'var(--pq-border)',
          'border-soft': 'var(--pq-border-soft)',
          'border-subtle': 'var(--pq-border-subtle)',
          'border-strong': 'var(--pq-border-strong)',
          text: 'var(--pq-text)',
          primary: 'var(--pq-text-primary)',
          'text-secondary': 'var(--pq-text-secondary)',
          'text-tertiary': 'var(--pq-text-tertiary)',
          'text-quaternary': 'var(--pq-text-quaternary)',
          muted: 'var(--pq-text-muted)',
          faint: 'var(--pq-text-faint)',
          accent: 'var(--pq-accent)',
          'accent-hover': 'var(--pq-accent-hover)',
          'accent-soft': 'var(--pq-accent-soft)',
          'accent-bg': 'var(--pq-accent-bg)',
          'accent-bg-hover': 'var(--pq-accent-bg-hover)',
          'accent-border': 'var(--pq-accent-border)',
          'accent-border-strong': 'var(--pq-accent-border-strong)',
          'accent-ring': 'var(--pq-accent-ring)',
          'accent-shadow': 'var(--pq-accent-shadow)',
          'accent-text': 'var(--pq-accent-text)',
          'accent-button-bg': 'var(--pq-accent-button-bg)',
          'accent-button-bg-hover': 'var(--pq-accent-button-bg-hover)',
          'accent-button-text': 'var(--pq-accent-button-text)',
          success: 'var(--pq-success)',
          'success-bg': 'var(--pq-success-bg)',
          warning: 'var(--pq-warning)',
          'warning-bg': 'var(--pq-warning-bg)',
          error: 'var(--pq-error)',
          'error-bg': 'var(--pq-error-bg)',
          info: 'var(--pq-info)',
          'info-bg': 'var(--pq-info-bg)',
        },
      },
      boxShadow: {
        panel: 'var(--pq-shadow-soft)',
        float: 'var(--pq-shadow-float)',
        dialog: 'var(--pq-shadow-dialog)',
      },
      borderRadius: {
        pq: 'var(--pq-radius-md)',
        'pq-sm': 'var(--pq-radius-sm)',
        'pq-lg': 'var(--pq-radius-lg)',
      },
      transitionDuration: {
        fast: '120ms',
        DEFAULT: '200ms',
        slow: '300ms',
      },
    },
  },
  plugins: [],
} satisfies Config;
